name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec # v9
      - name: Set up Python 3.10
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install
      - name: Run linting
        run: |
          poetry run ruff .
      - name: Run type checking
        run: |
          poetry run mypy .
      - name: Download spacy model
        run: |
          poetry run python -m spacy download de_core_news_sm
      - name: Run tests
        run: |
          poetry run pytest --cov=fun_sentence_splitter
