name: publish

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@4b3306307f536bbfcb559603629b3b4f6aef5ab8 # v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
